### ISSUE TITLE
Adding documents attaching feature

### ISSUE THREAD

**Issue by testingname2020** [RameshKannan20/WhatsApp_Development_Summa#3]
Hi Ramesh,
It would be added advantage if you can add the feature 'attaching document' feature in your whatsapp code.

**Comment by RameshKannan20** [comment]
Hi Testingname2020, Thanks for suggesting this feature. We will add this feature and let you know.

**Comment by RameshKannan20** [comment]
Hi Testingname2020, Thanks for your suggestion. Your features attaching document is added in the code
